name: release-project
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      bundle_filename:
        required: true
        type: string
      working_dir:
        required: true
        type: string

runs:
  using: composite
  defaults:
    run:
      working-directory: ${{ inputs.working_dir }}
  steps:
    - name: Install Dependencies
      uses: ./.github/actions/prepare-build

    - name: Build Artifact
      run: yarn build

    - name: Upload artifact
      working-directory: ${{ inputs.working_dir }}/dist
      run: |
        zip -r ${{ inputs.bundle_filename }} .
        gh release upload ${{ inputs.tag }} ${{ inputs.bundle_filename }}
