name: prepare-build
description: Prepare the build environment
runs:
  using: composite
  steps:
    - name: Install yarn dependencies
      uses: ./.github/actions/yarn-cache

    - name: Restore Rust cache
      uses: ./.github/actions/rust-cache
      with:
        cache-name: build

    - name: Setup Rust toolchain
      run: rustup toolchain add nightly-2025-03-27
      shell: bash

    - name: Apt update
      run: sudo apt update
      shell: bash

    - name: Install protoc
      run: sudo apt-get install -y protobuf-compiler
      shell: bash
