name: prepare-build

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install yarn dependencies
      uses: ./.github/actions/yarn-cache

    - name: Restore Rust cache
      uses: ./.github/actions/rust-cache
      with:
        cache-name: build

    - name: Install protoc
      run: sudo apt-get install -y protobuf-compiler
