# Uncomment the following lines to define your default indexer and rpc urls
#indexer_url = ""
#rpc_url = ""
#masp_indexer_url = ""
#localnet_enabled = false

github_chain_registry_base_url = "https://raw.githubusercontent.com/anoma/namada-chain-registry/refs/heads/main"
github_namada_interface_url = "https://raw.githubusercontent.com/anoma/namada-interface/refs/heads/main"
